base/urls.py
from django.urls import path

from . import views

app_name = 'base'


urlpatterns = [
    path('index', views.index, name='index'),
    path('', views.get_car_image, name='car_image'),
    path('modelList/<str:car_model>/', views.get_model_list, name='modelList'),
]

carInformation/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('base.urls')),
    path('admin/', admin.site.urls),
]

base/models.py
from django.db import models

# Create your models here.

base/views.py
import os

from django.shortcuts import render
from django.views.decorators.http import require_GET

from .config.config_car import CarMap
from .config.config_request import RequestConfig
from .fetch import FetchAPI


# Create your views here.
@require_GET
def index(request):
    request_url = RequestConfig.REQUEST_URL.value
    header_value = RequestConfig.HEADERS.value
    responded_api_object = FetchAPI(request_url, header_value)

    context = {
        'cars_list': responded_api_object.get_carlist(),
        # cars_set to remove the duplicated car maker
        'cars_set': set(car.maker for car in responded_api_object.get_carlist()),
    }
    # print(set(car.maker for car in responded_api_object.get_carlist()))
    return render(request, "pages/index.html", context)


@require_GET
def get_car_image(request):
    name_to_img_dict = {}
    file_list = [filename for filename in os.listdir(CarMap.CAR_IMG_DIR) if not filename.startswith('.')]
    for file in file_list:
        # getting rid of ".jpg"
        name_to_img_dict[file[:-4]] = file
    context = {
        'files': name_to_img_dict,
    }
    return render(request, "pages/carList.html", context)


@require_GET
def get_model_list(request, car_model):
    request_url = RequestConfig.REQUEST_URL.value
    header_value = RequestConfig.HEADERS.value
    responded_api_object = FetchAPI(request_url, header_value)
    car_model_list = responded_api_object.get_carlist(car_model)

    context = {
        'cars': car_model_list,
        # one car maker/car image to many car model
        'car_maker': car_model_list[0].maker,
        'car_img_jpg': CarMap.CAR_TO_IMG[car_model_list[0].maker]
    }
    return render(request, "pages/modelList.html", context)

base/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<!-- Bootstrap CSS -->

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">
</body>
<head>
    <meta charset="UTF-8">
    <title>Car Warehouse</title>
</head>
<body>
    <header>{% include 'partials/navbar.html' %}</header>
    <div class="container ">

        {% block index %}
        {% endblock %}

        {% block modelList %}
        {% endblock %}

        {% block carList %}
        {% endblock %}

    </div>
</body>
</html>

base/templates/pages/carList.html
{% extends 'base.html' %}
{% load static %}


{% block carList %}
<div class="row">
    {% for car, car_img in files.items %}
    <div class="col-4 col-xl-4 text-center mt-5 mb-2 border">
        <a href="{% url 'base:modelList' car %}">
            <img src="{% static 'img/'|add:car_img %}" alt="{{ car }}">
        </a>
    </div>
    {% endfor %}
</div>
{% endblock %}

base/templates/pages/index.html
{% extends 'base.html' %}
{% load static %}

{% block index %}
<div class="row">
    {% for car in cars_list %}
    <div class="col-4 col-xl-4 text-center p-2 mt-2 mb-2 border">
        <h2>{{ car.maker }}</h2>
        <h4>Model: {{ car.model }}</h4>
        <img src="{% static 'img/'|add:car.image_jpg %}" alt="{{ car.maker }}">
    </div>
    {% endfor %}
</div>
{% endblock %}

base/templates/pages/modelList.html
{% extends 'base.html' %}
{% load static %}


{% block modelList %}
<div>
    <h1 class="p-5 text-center">{{ car_maker }}</h1>
    <div class="justify-content-center">
        <img src="{% static 'img/'|add:car_img_jpg %}" class="rounded mx-auto d-block mb-4" alt="{{ car.maker }}">
    </div>

</div>
<table class="table">
  <thead>
    <tr>
      <th class="text-center" scope="col">Car Name</th>
      <th class="text-center" scope="col">Car Model</th>
    </tr>
  </thead>
  <tbody>
    {% for car in cars %}
    <tr>
      <td class="text-center">{{ car.maker }}</td>
      <td class="text-center">{{ car.model }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

base/templates/partials/navbar.html
{% load static %}


<div id="title" class="d-flex justify-content-around mt-3">
  <span class="my-auto">
    <h1 class="">Car Library</h1>
  </span>

  <span>
    <label for="cars">Choose a car:</label>
      <select class="navbar-brand custom-select" name="cars" id="cars">
        {% for car in files.keys %}
          <option value="{{ car }}">{{ car }}</option>
        {% endfor %}
      </select>
  </span>

  <span>
    <label>Year:</label>
    <select class="navbar-brand  custom-select" id='date-dropdown'></select>
  </span>

  <script>
    let dateDropdown = document.getElementById('date-dropdown');

    let currentYear = new Date().getFullYear();
    let earliestYear = 2000;

    while (currentYear >= earliestYear) {
      let dateOption = document.createElement('option');
      dateOption.text = currentYear;
      dateOption.value = currentYear;
      dateDropdown.add(dateOption);
      currentYear -= 1;
    }
  </script>
</div>